# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile is used with the vagrant package command to ensure that
# packaged vagrant boxes use the GUI, which does not happen by default for
# some reason.
# Also maps included files
Vagrant.configure(2) do |config|
  # Virtualbox GUI
  config.vm.provider "virtualbox" do |v|
    v.gui = true
  end


  # Sync ./scripts --> /scripts, etc
  ["scripts", "docker"].each do |folder|
    folder_path = File.expand_path("../#{folder}", __FILE__)
    config.vm.synced_folder folder_path, "/#{folder}"
  end
end
